from .Generation import BLOCK_SIZE
'''Miscalleneous Variables'''
SLEEP_VELOCITY_THRESHOLD = .0001
ITEM_PICKUP_TIME = 3.0
ENTITY_MAX_LIFESPAN = 1 * 10 #seconds
ITEM_SIZE = BLOCK_SIZE//2
PARTICLE_SIZE = BLOCK_SIZE // 8
ZERO = 0


'''Game States'''
MAIN_MENU = 0
RUNNING = 1
SETTINGS = 2

'''Types of Ground'''
GROUND_DIRT = 1
GROUND_STONE = 2
GROUND_WATER = 3
GROUND_GRASS = 4