from .Generation import BLOCK_SIZE
'''Miscalleneous Variables'''
SLEEP_VELOCITY_THRESHOLD = .0001
ITEM_PICKUP_TIME = 3.0
ITEM_SIZE = BLOCK_SIZE//2
PARTICLE_SIZE = BLOCK_SIZE // 8
ZERO = 0
POSITIVE_INFINITY = float('inf')
NEGATIVE_INFINITY = float('-inf')

'''Game States'''
MAIN_MENU = 0
RUNNING = 1
SETTINGS = 2
GENERATING_WORLD = 3
CHARACTER_CREATION = 4
WORLD_SELECT = 5


'''Types of Ground'''
GROUND_DIRT = 1
GROUND_STONE = 2
GROUND_WATER = 3
GROUND_GRASS = 4