import os
import stat
dirname = os.path.dirname(__file__)

dirs = []

def BFSDirs(roots:list[str]):
    while roots:
        curdir = roots.pop(0)
        yield curdir
        for path in os.listdir(curdir):
            fqn = os.path.join(curdir,path)
            s = os.stat(fqn)
            if stat.S_ISDIR(s.st_mode):
                dirs.append(fqn)
                roots.append(fqn)


dirs = list(filter(lambda x:not os.path.basename(x).startswith('__') , BFSDirs([dirname])))
for dir in dirs:
    with open(os.path.join(dir,'__init__.py'),'w') as file:
        lines = ['#This file has been generated by {}/__main__.py\n'.format(os.path.basename(dirname))]
        exports:list[str] = []
        subdirs:list[str] = []
        for file_name in os.listdir(dir):
            fqn = os.path.join(dir,file_name)
            if file_name.startswith('__'): continue
            if file_name.endswith('.py') and os.path.isfile(fqn):
                exported_name = file_name.removesuffix('.py')
                exports.append(exported_name)
                lines.append(f'from .{exported_name} import {exported_name}\n')
            elif not file_name.startswith('__') and os.path.isdir(fqn):
                subdirs.append(file_name)
        lines = lines[:1] + [f'from . import {subdir}\n' for subdir in subdirs] +['\n'] + lines[1:]
        exports = subdirs + exports
        lines.append('\n\n')
        lines.append('__all__ = [\n  ')
        lines.append(repr(exports).replace(', ',',\n  ')[1:-1])
        lines.append('\n]\n')
        # lines.append('\',\n    \''.join(exports))
        # lines.append('\'\n]')
        file.writelines(lines)

